id: smart.who.int.l2-hhas
canonical: http://smart.who.int/l2-hhas
name: L2hhas
title: SMART L2 HHAS
description: SMART Guidelines L2 for Heat-Health Alert System (HHAS) is a set of specifications
  for the implementation of a Heat-Health Alert System. It provides a framework for
  countries to adapt and implement heat-health alert systems to protect public health
  during extreme heat events.
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: ci-build
publisher:
  name: WHO
  url: http://who.int
meta:
  profile:
  - SMARTImplementationGuide
pages:
  index.md:
    title: Home
    changes.md:
      title: Changes
    dependencies.md:
      title: Dependencies
    references.md:
      title: References
    adapting.md:
      title: Adapting Guidelines for Country use
    license.md:
      title: License
  business-requirements.md:
    title: Business Requirements
    concepts.md:
      title: Concepts
    health-interventions.md:
      title: Health Interventions
    personas.md:
      title: Generic Personas
    scenarios.md:
      title: User Scenarios
    business-processes.md:
      title: Business Processes
    dictionary.md:
      title: Data Dictionary
    decision-logic.md:
      title: Decision-support logic
    scheduling-logic.md:
      title: Scheduling logic
    indicators.md:
      title: Indicator and Performance Metrics
    functional-requirements.md:
      title: Functional Requirements
    non-functional-requirements.md:
      title: Non-functional Requirements
    system-requirements.md:
      title: System Requirements
  data-models-and-exchange.md:
    title: Data Models and Exchange
    system-actors.md:
      title: System Actors
    sequence-diagrams.md:
      title: Sequence Diagrams
    transactions.md:
      title: Transactions
    indicators-measures.md:
      title: Indicators and Measures
    codings.md:
      title: Codings
  deployment.md:
    title: Deployment
    security-privacy.md:
      title: Security and Privacy Considerations
    testing.md:
      title: Testing
    test-data.md:
      title: Test Data
    reference-implementations.md:
      title: Reference Implementations
    trust_domain.md:
      title: Trust Domains
    downloads.md:
      title: Downloads
  indices.md:
    title: Indices
    artifacts.html:
      title: Artifact Index
    maps.md:
      title: Mappings
  dak-api.md:
    title: DAK API Documentation Hub
menu:
  Home:
    Summary: index.html
    Changes: changes.html
    Dependencies: dependencies.html
    References: references.html
    Adapting and implementing: adapting.html
  Business Requirements:
    Concepts: concepts.html
    Health Interventions: health-interventions.html
    Generic Personas: personas.html
    User Scenarios: scenarios.html
    Business Processes: business-processes.html
    Data Dictionary: dictionary.html
    Decision-support Logic: decision-logic.html
    Scheduling Logic: scheduling-logic.html
    Indicator and Performance Metrics: indicators.html
    Functional Requirements: functional-requirements.html
    Non-functional Requirements: non-functional-requirements.html
    System Requirements: system-requirements.html
  Data Models and Exchange:
    System Actors: system-actors.html
    Sequence Diagrams: sequence-diagrams.html
    Transactions: transactions.html
    Indicators and Measures: indicators-measures.html
    Codings: codings.html
  Deployment:
    Security and Privacy Considerations: security-privacy.html
    Testing: testing.html
    Test Data: test-data.html
    Reference Implementations: reference-implementations.html
    Trust Domains: trust_domain.html
    Downloads: downloads.html
  Indices:
    Artifact Index: artifacts.html
    Mappings: maps.html
    DAK API: dak-api.html
dependencies:
  smart.who.int.base: 0.2.0
parameters:
  path-pages:
  - input/dictionary
  - input/decision-logic
  - input/business-processes
  - input/scheduling-logic
  - input/indicators
  - input/system-requirements
  - input/testing
